-- up:

CREATE TABLE IF NOT EXISTS community (
    id          serial primary key,
    name        varchar(40) NOT NULL,
    gate        varchar(40) NOT NULL,
    
    CONSTRAINT unique_community_name UNIQUE (name)
);

-- down:

DROP TABLE community;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'community'
);
