-- up:

CREATE TABLE IF NOT EXISTS structure_institute_add (
    id                serial primary key,
    structure         int REFERENCES structure(id) ON DELETE SET NULL,
    institute         int REFERENCES institute(id) ON DELETE SET NULL
);

-- down:

DROP TABLE structure_institute_add;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'structure_institute_add'
);
