-- up:

CREATE TABLE IF NOT EXISTS structure_community_add (
    id                serial primary key,
    structure         varchar(255) REFERENCES structure(id) ON DELETE SET NULL,
    community         varchar(255) REFERENCES community(id) ON DELETE SET NULL
);

-- down:

DROP TABLE structure_community_add;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'structure_community_add'
);
